### ISSUE TITLE
[DOC] Conda installation instructions on front page does not tell user to set channel_priority

### ISSUE THREAD

**Issue by vsong** [rapidsai/docs#352] opened 2023-03-26 20:05 UTC
## Report incorrect documentation

**Location of incorrect documentation**
https://docs.rapids.ai/install#selector
and https://rapids.ai/

**Describe the problems or issues found in the documentation**
This pertains to the Quick Start > Install with conda section.

The conda installation method for rapids requires `channel_priority` to be set to `flexible` in order for the conda solver to resolve, as stated in the installation docs. However, rapids.ai frontpage does not explicitly tell users to set this variable which leads to install errors, This is a problem because conda (and miniconda) sets `channel_priority` to `strict` by default.

**Steps taken to verify documentation is incorrect**
- Installed conda and miniconda on my Debian machine using the latest 23.03 installer and verified that .condarc has `channel_priority` set to `strict` by default.
- Tried running `conda create -n rapids-23.02 -c rapidsai -c conda-forge -c nvidia rapids=23.02 python=3.10 cudatoolkit=11.8` and the installation fails because the solver could not find a solution.

**Suggested fix for documentation**
On the front page, add the command `conda config --set channel_priority flexible` to the Quick Start > Install with conda section.

**Comment by exactlyallan** [comment] 2023-03-31 17:22
@taureandyernv @ajschmidt8 is this something we need to implement asap?

**Comment by taureandyernv** [comment] 2023-03-31 18:36
@vsong , can you update your conda install and try again?
```
#update the conda package manager to the latest version
conda update conda
#use conda to update Anaconda to the latest version
conda update anaconda
```

Usually when i see this, it's because the installed conda version is too old

**Comment by ajschmidt8** [comment] 2023-04-03 17:54
@vsong, thanks for opening this issue.

You are correct that RAPIDS does not currently support `channel_priority: strict`.

However, I can't seem to reproduce your claim that `miniconda` sets `channel_priority` to `strict` by default.

If you run the command below (which installs `miniconda` into a clean `ubuntu` container), you'll see that the default `channel_priority` value is `flexible`:

```sh
docker run \
  --rm \
  -it \
  --pull=always \
  ubuntu \
  bash -c \
    'apt update; \
    apt install -y wget; \
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh; \
    bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda; \
    ~/miniconda/bin/conda config --show | grep channel_priority'
```

This seems to be supported by the official conda docs below that state that the default value of `channel_priority` is `flexible`:

- https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html#strict-channel-priority

Therefore, I think our current disclaimer [here](https://docs.rapids.ai/install#selector) (shown in the screenshot below) is sufficient.

![image](https://user-images.githubusercontent.com/7400326/229588153-0f604dfa-f896-4f61-8f5c-b13490fe3f99.png)


I will close this issue, but feel free to provide any additional feedback if you find any issues with my statements above.

**Closed by ajschmidt8** 2023-04-03 17:54 UTC
Labels: ? - Needs Triage, doc
